name: Build MacOS ARM
description: Build MacOS ARM binary
runs:
  using: "composite"
  steps:
    - name: Get OpenOMF Version
      uses: ./.github/actions/version

    - name: Install Mac Dependencies
      shell: bash
      run: |
        brew update
        brew install confuse cunit enet libepoxy libnatpmp libxmp miniupnpc \
          opusfile sdl2-compat sdl2_mixer sdl3
        brew install coreutils create-dmg

    - name: Generate Release
      shell: bash
      run: |
        mkdir build-release && cd build-release
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=. ..
        make -j $(getconf _NPROCESSORS_ONLN)
        make -j $(getconf _NPROCESSORS_ONLN) install

    - name: Get openomf assets
      uses: ./.github/actions/assets

    - name: Extract openomf assets
      shell: bash
      run: unzip -j openomf-assets.zip -d build-release/openomf.app/Contents/Resources

    - name: Get openomf mods
      uses: ./.github/actions/fetch_mods

    - name: Extract openomf mods
      shell: bash
      run: |
        mkdir -p build-release/openomf.app/Contents/mods
        unzip -o openomf-mods.zip -d build-release/openomf.app/Contents/mods

    - name: Create DMG package
      shell: bash
      run: |
        create-dmg \
          --volname "OpenOMF" \
          --app-drop-link 300 150 \
          --hide-extension "OpenOMF.app" \
          "openomf_${{ env.OPENOMF_VERSION }}_macos26_arm.dmg" \
          "build-release/openomf.app/"

    - name: Mount DMG and Install OpenOMF
      shell: bash
      run: |
        hdiutil attach "openomf_${{ env.OPENOMF_VERSION }}_macos26_arm.dmg" \
          -nobrowse -mountpoint ./mounted_openomf
        cp -R ./mounted_openomf/openomf.app /Applications/
        hdiutil detach ./mounted_openomf

    - name: Verify openomf.app signature
      shell: bash
      run: |
        codesign --verify --deep --verbose=4 /Applications/openomf.app

    - name: Check openomf --version works
      shell: bash
      run: |
        set -o pipefail
        ret=0
        gtimeout 10 /Applications/openomf.app/Contents/MacOS/openomf \
          --version 2>&1 | tee $RUNNER_TEMP/version || ret=$?
        if [ "$ret" -ne 1 ]; then
          echo "openomf --version exit value: $ret"
          if [ "$ret" -eq 124 ]; then
            echo "openomf --version timed out"
          fi
          exit 1
        fi
        if ! grep -q "$OPENOMF_VERSION" "$RUNNER_TEMP/version"; then
          echo "$RUNNER_TEMP/version does not include $OPENOMF_VERSION"
          exit 1
        fi

    - name: Run REC tests
      shell: bash
      env:
        OPENOMF_RESOURCE_PATH: /Applications/openomf.app/Contents
      run: ./run_rectests.sh build-release

    - name: Upload DMG artifact
      uses: actions/upload-artifact@v7
      with:
        name: openomf_${{ env.OPENOMF_VERSION }}_macos26_arm
        path: openomf_${{ env.OPENOMF_VERSION }}_macos26_arm.dmg
        if-no-files-found: error
