#ifndef MENU_WIDGET_IDS_H
#define MENU_WIDGET_IDS_H

#define NETWORK_BUTTON_ID 100
#define NETWORK_CONNECT_BUTTON_ID 101
#define NETWORK_LISTEN_BUTTON_ID 102
#define NETWORK_CONNECT_IP_BUTTON_ID 103

#endif // MENU_WIDGET_IDS_H
