FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git \
    libsdl2-dev libsdl2-mixer-dev \
    libconfuse-dev libenet-dev \
    libxmp-dev libpng-dev zlib1g-dev \
    libopusfile-dev libepoxy-dev \
    libminiupnpc-dev libnatpmp-dev \
    libssl-dev \
    libasio-dev \
    libcunit1-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
