#!/bin/sh -x
EMSHIT=$(realpath emshit)
emcmake cmake . -Bemscripten \
 -DZLIB_INCLUDE_DIR=$EMSHIT -DZLIB_LIBRARY=$EMSHIT/libz.a \
 -DPNG_PNG_INCLUDE_DIR=$EMSHIT -DPNG_LIBRARY=$EMSHIT/libpng.a \
 -DSDL2_INCLUDE_DIR=$EMSHIT -DSDL2_LIBRARY=$EMSHIT/libSDL2.a \
 -DENET_INCLUDE_DIR=$EMSHIT -DENET_LIBRARY=$EMSHIT/libenet.a \
 -DCONFUSE_INCLUDE_DIR=$EMSHIT/confuse -DCONFUSE_LIBRARY=$EMSHIT/confuse/libconfuse.a \
 -DLIBINTL_INCLUDE_DIR=$EMSHIT -DLIBINTL_LIB_FOUND=1 -DLIBINTL_LIBRARIES="" \
 -DOPENAL_LIBRARY="" \
 -DVERBOSE=1
