if(VCPKG_TOOLCHAIN)
    find_package(Argtable3 CONFIG)
    if(Argtable3_FOUND)
        set(ARGTABLE3_FOUND ON)
        set(ARGTABLE3_LIBRARY argtable3::argtable3)
        set(ARGTABLE3_INCLUDE_DIR)
        set(ARGTABLE3_INCLUDE_DIRS)
        set(ARGTABLE3_LIBRARIES ${ARGTABLE3_LIBRARY})

        mark_as_advanced(ARGTABLE3_INCLUDE_DIR ARGTABLE3_LIBRARY)
        return()
    endif(Argtable3_FOUND)
endif(VCPKG_TOOLCHAIN)

set(ARGTABLE3_SEARCH_PATHS
    /usr/local
    /usr
    /opt
)

find_path(ARGTABLE3_INCLUDE_DIR argtable3.h
    HINTS
    PATH_SUFFIXES include
    PATHS ${ARGTABLE3_SEARCH_PATHS}
)
find_library(ARGTABLE3_LIBRARY argtable3
    HINTS
    PATH_SUFFIXES lib64 lib
    PATHS ${ARGTABLE3_SEARCH_PATHS}
)

if(ARGTABLE3_INCLUDE_DIR AND ARGTABLE3_LIBRARY)
   set(ARGTABLE3_FOUND TRUE)
endif()

if(ARGTABLE3_FOUND)
    set(ARGTABLE3_LIBRARIES ${ARGTABLE3_LIBRARY})
    set(ARGTABLE3_INCLUDE_DIRS ${ARGTABLE3_INCLUDE_DIR})
    message(STATUS "Found Argtable3: ${ARGTABLE3_LIBRARIES}")
endif()

mark_as_advanced(ARGTABLE3_INCLUDE_DIR ARGTABLE3_LIBRARY ARGTABLE3_SEARCH_PATHS)
