
SET(CONFIG_SEARCH_PATHS
    /usr/local/
    /usr
    /opt
)

FIND_PATH(CONFIG_INCLUDE_DIR libconfig.h 
    HINTS 
    PATH_SUFFIXES include
    PATHS ${CONFIG_SEARCH_PATHS}
)
FIND_LIBRARY(CONFIG_LIBRARY config 
    HINTS
    PATH_SUFFIXES lib64 lib bin
    PATHS ${CONFIG_SEARCH_PATHS}
)

IF(CONFIG_INCLUDE_DIR AND CONFIG_LIBRARY)
   SET(CONFIG_FOUND TRUE)
ENDIF (CONFIG_INCLUDE_DIR AND CONFIG_LIBRARY)


IF(CONFIG_FOUND)
    MESSAGE(STATUS "Found libConfig: ${CONFIG_LIBRARY}")
ELSE(CONFIG_FOUND)
    MESSAGE(WARNING "Could not find libConfig")
ENDIF(CONFIG_FOUND)