
FIND_PACKAGE(Threads)

SET(SDLMIXER_SEARCH_PATHS
    /usr/local/
    /usr/
)

FIND_PATH(SDLMIXER_INCLUDE_DIR SDL2/SDL_mixer.h
    HINTS
    PATH_SUFFIXES include
    PATHS ${SDLMIXER_SEARCH_PATHS}
)

FIND_LIBRARY(SDLMIXER_LIBRARY
    NAMES SDL2_mixer
    HINTS
    PATH_SUFFIXES lib64 lib
    PATHS ${SDLMIXER_SEARCH_PATHS}
)

IF(SDLMIXER_INCLUDE_DIR AND SDLMIXER_LIBRARY)
   SET(SDLMIXER_FOUND TRUE)
ENDIF (SDLMIXER_INCLUDE_DIR AND SDLMIXER_LIBRARY)

IF(SDLMIXER_FOUND)
    MESSAGE(STATUS "Found SDL_Mixer: ${SDLMIXER_LIBRARY}")
ELSE(SDLMIXER_FOUND)
    MESSAGE(WARNING "Could not find SDL_Mixer")
ENDIF(SDLMIXER_FOUND)