set(LIBNATPMP_SEARCH_PATHS /usr/local/ /usr /opt)

find_path(
  LIBNATPMP_INCLUDE_DIR natpmp.h
  HINTS
  PATH_SUFFIXES include
  PATHS ${LIBNATPMP_SEARCH_PATHS})
find_library(
  LIBNATPMP_LIBRARY natpmp
  HINTS
  PATH_SUFFIXES lib64 lib bin
  PATHS ${LIBNATPMP_SEARCH_PATHS})

if(LIBNATPMP_INCLUDE_DIR AND LIBNATPMP_LIBRARY)
  set(LIBNATPMP_FOUND TRUE)
endif(LIBNATPMP_INCLUDE_DIR AND LIBNATPMP_LIBRARY)

if(LIBNATPMP_FOUND)
  message(STATUS "Found libnatpmp: ${LIBNATPMP_LIBRARY}")
else(LIBNATPMP_FOUND)
  message(WARNING "Could not find libnatpmp")
endif(LIBNATPMP_FOUND)

mark_as_advanced(LIBNATPMP_INCLUDE_DIR LIBNATPMP_LIBRARY LIBNATPMP_SEARCH_PATHS)
