
SET(AO_SEARCH_PATHS
    /usr/local
    /usr
    /opt
)

FIND_PATH(AO_INCLUDE_DIR ao/ao.h 
    HINTS
    PATH_SUFFIXES include
    PATHS ${AO_SEARCH_PATHS}
)
FIND_LIBRARY(AO_LIBRARY ao 
    HINTS
    PATH_SUFFIXES lib64 lib
    PATHS ${AO_SEARCH_PATHS}
)

IF(AO_INCLUDE_DIR AND AO_LIBRARY)
   SET(AO_FOUND TRUE)
ENDIF (AO_INCLUDE_DIR AND AO_LIBRARY)

IF(WIN32)
    IF(AO_FOUND)
        SET(AO_LIBRARY ${AO_LIBRARY} winmm)
    ENDIF(AO_FOUND)
ENDIF(WIN32)

IF(AO_FOUND)
    MESSAGE(STATUS "Found libao: ${AO_LIBRARY}")
ELSE(AO_FOUND)
    MESSAGE(WARNING "Could not find libao")
ENDIF(AO_FOUND)