set(MINIUPNPC_SEARCH_PATHS /usr/local/ /usr /opt)

find_path(
  MINIUPNPC_INCLUDE_DIR miniupnpc/miniupnpc.h
  HINTS
  PATH_SUFFIXES include
  PATHS ${MINIUPNPC_SEARCH_PATHS})
find_library(
  MINIUPNPC_LIBRARY miniupnpc
  HINTS
  PATH_SUFFIXES lib64 lib bin
  PATHS ${MINIUPNPC_SEARCH_PATHS})

if(MINIUPNPC_INCLUDE_DIR AND MINIUPNPC_LIBRARY)
  set(MINIUPNPC_FOUND TRUE)
endif(MINIUPNPC_INCLUDE_DIR AND MINIUPNPC_LIBRARY)

if(MINIUPNPC_FOUND)
  message(STATUS "Found libminiupnpc: ${MINIUPNPC_LIBRARY}")
else(MINIUPNPC_FOUND)
  message(WARNING "Could not find libminiupnpc")
endif(MINIUPNPC_FOUND)

mark_as_advanced(MINIUPNPC_INCLUDE_DIR MINIUPNPC_LIBRARY MINIUPNPC_SEARCH_PATHS)
