
SET(SHADOWDIVE_SEARCH_PATHS
    /usr/local/
    /usr
    /opt
)

FIND_PATH(SHADOWDIVE_INCLUDE_DIR shadowdive/shadowdive.h
    HINTS ${SHADOWDIVE_ROOT}
    PATH_SUFFIXES include include/shadowdive
    PATHS ${SHADOWDIVE_SEARCH_PATHS}
)
FIND_LIBRARY(SHADOWDIVE_LIBRARY shadowdive
    HINTS ${SHADOWDIVE_ROOT}
    PATH_SUFFIXES lib64 lib bin
    PATHS ${SHADOWDIVE_SEARCH_PATHS}
)

IF(SHADOWDIVE_INCLUDE_DIR AND SHADOWDIVE_LIBRARY)
   SET(SHADOWDIVE_FOUND TRUE)
ENDIF (SHADOWDIVE_INCLUDE_DIR AND SHADOWDIVE_LIBRARY)


IF(SHADOWDIVE_FOUND)
    MESSAGE(STATUS "Found Shadowdive: ${SHADOWDIVE_LIBRARY}")
ELSE(SHADOWDIVE_FOUND)
    MESSAGE(WARNING "Could not find Shadowdive")
ENDIF(SHADOWDIVE_FOUND)