
SET(OGG_SEARCH_PATHS
    /usr/local/
    /usr
    /opt
)

FIND_PATH(OGG_INCLUDE_DIR ogg/ogg.h
    HINTS ${OGG_ROOT}
    PATH_SUFFIXES include
    PATHS ${OGG_SEARCH_PATHS}
)
FIND_LIBRARY(OGG_LIBRARY ogg
    HINTS ${OGG_ROOT}
    PATH_SUFFIXES lib64 lib bin
    PATHS ${OGG_SEARCH_PATHS}
)

IF(OGG_INCLUDE_DIR AND OGG_LIBRARY)
   SET(OGG_FOUND TRUE)
ENDIF (OGG_INCLUDE_DIR AND OGG_LIBRARY)


IF(OGG_FOUND)
    MESSAGE(STATUS "Found Ogg: ${OGG_LIBRARY}")
ELSE(OGG_FOUND)
    MESSAGE(WARNING "Could not find Ogg")
ENDIF(OGG_FOUND)
