
SET(LIBCONFIG_SEARCH_PATHS
    /usr/local/
    /usr
    /opt
)

FIND_PATH(LIBCONFIG_INCLUDE_DIR libconfig.h 
    HINTS 
    PATH_SUFFIXES include
    PATHS ${LIBCONFIG_SEARCH_PATHS}
)
FIND_LIBRARY(LIBCONFIG_LIBRARY libconfig 
    HINTS ${SHADOWDIVE_ROOT}
    PATH_SUFFIXES lib64 lib bin
    PATHS ${LIBCONFIG_SEARCH_PATHS}
)

IF(LIBCONFIG_INCLUDE_DIR AND LIBCONFIG_LIBRARY)
   SET(LIBCONFIG_FOUND TRUE)
ENDIF (LIBCONFIG_INCLUDE_DIR AND LIBCONFIG_LIBRARY)


IF(LIBCONFIG_FOUND)
    MESSAGE(STATUS "Found libConfig: ${LIBCONFIG_LIBRARY}")
ELSE(LIBCONFIG_FOUND)
    MESSAGE(WARNING "Could not find libConfig")
ENDIF(LIBCONFIG_FOUND)