macro(openomf_strings)
    # strings new in OpenOMF
    openomf_string(LangLanguage "Language name")
    openomf_string(LangEncoding "LNG Text Encoding")
endmacro()

macro(base_strings)
    # strings from OMF 2097
    from_base(LangPilot "Pilots" 20..=30)
    from_base(LangPilotDescription "Pilot Biography" 135..=145)
    from_base(LangRobot "Robots" 31..=41)
    from_base(LangRobotDescription "Robot Description" 492..=502)
    from_base(LangArena "Arena Name" 56..=60)
    from_base(LangArenaDescription "Arena Description" 66..=70)
    from_base(LangPronoun "Newsroom Pronouns" 81..=86)
    from_base(LangNewsroomUnrankedChallengerDialog "Newsroom Unrnkd Chlngr Dialog" 79)
    from_base(LangNewsroomUnrankedChallenger "Newsroom Unranked Challenger" 77..=78)
    from_base(LangNewsroomNewChampion "Newsroom New Champion" 79)
    from_base(LangNewsroomReport "Newsroom Reports" 87..=134)
    from_base(LangCpuDifficulty "CPU Difficulty" 343..=349)
    from_base(LangTooPatheticDialog "Too Pathetic Dialog" 748)
    from_base(LangTooPatheticInsult "Too Pathetic Insult" 747)
    from_base(LangVsInsult1 "VS Insult" 749..=869)
    from_base(LangVsInsult2 "VS Insult Reply" 870..=990)
    from_base(LangPlug "Plug says" 587..=602)
    from_base(LangPilotStatPower "Pilot Power Stat" 216)
    from_base(LangPilotStatSpeed "Pilot Speed Stat" 217)
    from_base(LangPilotStatEndurance "Pilot Endurance Stat" 218)
    from_base(LangChooseYourPilot "Choose Pilot" 187)
    from_base(LangChooseYourRobot "Choose Robot" 186)
    from_base(LangSceneEnd "SCENE_END text" 992)
    from_base(LangSceneEnd1 "SCENE_END1 per-pilot" 993..=1002)
    from_base(LangSceneEnd2 "SCENE_END2 per-pilot" 1003..=1012)
    from_base(LangSelectTournament "Select a Tournament" 486)
    from_base(LangSelectPhotoForChr "Select Photo for Pilot" 224)
    from_base(LangSelectChrToLoad "Select chr to load" 225)
    from_base(LangSelectChrToDelete "Select chr to delete" 226)
    from_base(LangSelectOpponent "Select Opponent" 227)
    from_base(LangTrainingTitle "Training Title" 512..=514)
    from_base(LangTrainingConfirmation "Training Confirmation" 515..=517)
    from_base(LangTrainingHelp "Training Help" 533..=535)
    from_base(LangTrainingDone "Leave Training" 536)
    from_base(LangTradeGainCash "Trade, gain cash" 518)
    from_base(LangTradeSpendCash "Trade, spend cash" 519)
    from_base(LangTradeEquitable "Trade, equitable" 520)
    from_base(LangButtonSelect "\"Select\" button" 223)
    from_base(LangTournamentFight "Tournament: Fight %s" 223)
    from_base(LangEnterTrainingHelp "Enter Training Help" 538)
    from_base(LangBuyUpgradesHelp "Buy Upgrade Kits Help" 539)
    from_base(LangSellUpgradesHelp "Sell Upgrade Kits Help" 540)
    from_base(LangChrLoadHelp "Pilot Load Help" 541)
    from_base(LangChrCreateHelp "Pilot Create Help" 542)
    from_base(LangChrDeleteHelp "Pilot Delete Help" 543)
    from_base(LangTournamentSimHelp "Enter Simulator Help" 544)
    from_base(LangTournamentQuitHelp "Close Tournament-Mode Help" 545)
    from_base(LangTournamentRegisterHelp "Tournament Register Help" 546)
    from_base(LangTournamentDifficulty "Tournament Difficulty" 444..=447)
    from_base(LangNo "No" 228)
    from_base(LangYes "Yes" 229)
    from_base(LangPromptChrName "Character Name Prompt" 192)
    from_base(LangCustomizeColor1 "Robot Primary color" 547)
    from_base(LangCustomizeColor2 "Robot Secondary color" 549)
    from_base(LangCustomizeColor3 "Robot Third color" 551)
    from_base(LangUpgradePowerSell "Sell Power Upgrade" 553)
    from_base(LangUpgradePowerBuy "Buy Power Upgrade" 554)
    from_base(LangUpgradeSpeedSell "Sell Speed Upgrade" 557)
    from_base(LangUpgradeSpeedBuy "Buy Speed Upgrade" 558)
    from_base(LangUpgradeArmorSell "Sell Armor Upgrade" 561)
    from_base(LangUpgradeArmorBuy "Buy Armor Upgrade" 562)
    from_base(LangUpgradeStunResistanceSell "Sell Stun Res. Upgrade" 563)
    from_base(LangUpgradeStunResistanceBuy "Buy Stun Res. Upgrade" 564)
    from_base(LangTradeHelp "Trade Robot tooltip" 565)
    from_base(LangTradeNoneAvailable "No Robots Available" 488)
    from_base(LangTradeAvailable "Robots Available:" 461)
    from_base(LangUpgradeQuitSell "leave upgrade sell" 567)
    from_base(LangUpgradeQuitBuy "leave upgrade buy" 568)
endmacro()
