# This file is used by BuildLanguages.cmake to make resources/generated_languages.h

# lang_str(<enum variant> [<str count>])
# The <enum variant> is what's used in the C code to refer to this language string.
# Specifying a <str count> allows for a range of lang strs to be added under one name

# strings from OMF 2097
lang_str(LangPilot 11)
lang_str(LangPilotDescription 11)
lang_str(LangRobot 11)
lang_str(LangRobotDescription 11)
lang_str(LangArena 5)
lang_str(LangArenaDescription 5)
lang_str(LangPronoun 6)
lang_str(LangNewsroomUnrankedChallengerDialog)
lang_str(LangNewsroomUnrankedChallenger 2)
lang_str(LangNewsroomNewChampion)
lang_str(LangNewsroomReport 48)
lang_str(LangCpuDifficulty 7)
lang_str(LangTooPatheticDialog)
lang_str(LangTooPatheticInsult)
lang_str(LangVsInsult1 121)
lang_str(LangVsInsult2 121)
lang_str(LangPlug 16)
lang_str(LangPilotStatPower)
lang_str(LangPilotStatSpeed)
lang_str(LangPilotStatEndurance)
lang_str(LangChooseYourPilot)
lang_str(LangChooseYourRobot)
lang_str(LangSceneEnd)
lang_str(LangSceneEnd1 10)
lang_str(LangSceneEnd2 10)
lang_str(LangSelectTournament)
lang_str(LangSelectPhotoForChr)
lang_str(LangSelectChrToLoad)
lang_str(LangSelectChrToDelete)
lang_str(LangSelectOpponent)
lang_str(LangTrainingTitle 3)
lang_str(LangTrainingConfirmation 3)
lang_str(LangTrainingHelp 3)
lang_str(LangTrainingDone)
lang_str(LangTradeGainCash)
lang_str(LangTradeSpendCash)
lang_str(LangTradeEquitable)
lang_str(LangButtonSelect)
lang_str(LangTournamentFight)
lang_str(LangEnterTrainingHelp)
lang_str(LangBuyUpgradesHelp)
lang_str(LangSellUpgradesHelp)
lang_str(LangChrLoadHelp)
lang_str(LangChrCreateHelp)
lang_str(LangChrDeleteHelp)
lang_str(LangTournamentSimHelp)
lang_str(LangTournamentQuitHelp)
lang_str(LangTournamentRegisterHelp)
lang_str(LangTournamentDifficulty 4)
lang_str(LangNo)
lang_str(LangYes)
lang_str(LangPromptChrName)
lang_str(LangCustomizeColor1)
lang_str(LangCustomizeColor2)
lang_str(LangCustomizeColor3)
lang_str(LangUpgradePowerSell)
lang_str(LangUpgradePowerBuy)
lang_str(LangUpgradeSpeedSell)
lang_str(LangUpgradeSpeedBuy)
lang_str(LangUpgradeArmorSell)
lang_str(LangUpgradeArmorBuy)
lang_str(LangUpgradeStunResistanceSell)
lang_str(LangUpgradeStunResistanceBuy)
lang_str(LangTradeHelp)
lang_str(LangTradeNoneAvailable)
lang_str(LangTradeAvailable)
lang_str(LangUpgradeQuitSell)
lang_str(LangUpgradeQuitBuy)
# strings new in OpenOMF
lang_str(LangLanguage)
