
SET(ARGTABLE2_SEARCH_PATHS
    /usr/local
    /usr
    /opt
)

FIND_PATH(ARGTABLE2_INCLUDE_DIR argtable2.h 
    HINTS
    PATH_SUFFIXES include
    PATHS ${ARGTABLE2_SEARCH_PATHS}
)
FIND_LIBRARY(ARGTABLE2_LIBRARY argtable2 
    HINTS
    PATH_SUFFIXES lib64 lib
    PATHS ${ARGTABLE2_SEARCH_PATHS}
)

IF(ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)
   SET(ARGTABLE2_FOUND TRUE)
ENDIF (ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)


IF(ARGTABLE2_FOUND)
    MESSAGE(STATUS "Found Argtable2: ${ARGTABLE2_LIBRARY}")
ELSE(ARGTABLE2_FOUND)
    MESSAGE(WARNING "Could not find Argtable2")
ENDIF(ARGTABLE2_FOUND)