name: Build MSVC
description: Build MSVC binary
inputs:
  arch:
    description: Architecture
    required: true
  build_languages:
    description: Whether to build languages files or not
    required: true
runs:
  using: "composite"
  steps:
    - name: Get OpenOMF Version
      uses: ./.github/actions/version

    - name: Prepare VCPKG
      # must be done *after* openomf has been checked out
      uses: johnwason/vcpkg-action@v7.0.1
      id: prepare-vcpkg
      with:
        manifest-dir: ${{ github.workspace }}
        triplet: ${{ inputs.arch }}-windows-static
        token: ${{ github.token }}
        extra-args: --x-feature ci-deps

    - uses: lukka/get-cmake@latest

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake (${{ inputs.arch }})
      shell: pwsh
      run: >
        cmake -S . -B build-msvc
        ${{ steps.prepare-vcpkg.outputs.vcpkg-cmake-config }}
        -A ${{ inputs.arch }}
        -DBUILD_LANGUAGES=${{ inputs.build_languages }}

    - name: Build openomf
      shell: pwsh
      run: cmake --build build-msvc --config Release --target openomf

    - name: Get openomf assets
      uses: ./.github/actions/assets

    - name: Extract openomf assets
      shell: pwsh
      run: |
        Expand-Archive openomf-assets.zip -PassThru
        mkdir install/openomf/resources
        Move-Item -Path openomf-assets/OMF2097/* -Destination install/openomf/resources/ -Force -PassThru

    - name: Install openomf
      shell: pwsh
      run: cmake --install build-msvc --config Release --prefix install

    - name: Generate ZIP package
      shell: pwsh
      run: |
        cd install
        Compress-Archive -Path openomf -DestinationPath openomf_${{ env.OPENOMF_VERSION }}_windows_msvc_${{ inputs.arch }}.zip -PassThru

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: openomf_${{ env.OPENOMF_VERSION }}_windows_msvc_${{ inputs.arch }}
        path: install/openomf_${{ env.OPENOMF_VERSION }}_windows_msvc_${{ inputs.arch }}.zip
        if-no-files-found: error
