#ifndef _COMMON_DEFINES_H
#define _COMMON_DEFINES_H

extern const char *difficulty_choices[];
extern const char *round_types[];
extern const char *pilot_names[];
extern const char *har_names[];

enum {
    DIFFICULTY_AI_PUNCHING_BAG = 0,
    DIFFICULTY_AI_ROOKIE,
    DIFFICULTY_AI_VETERAN,
    DIFFICULTY_AI_WORLD_CLASS,
    DIFFICULTY_AI_CHAMPION,
    DIFFICULTY_AI_DEADLY,
    DIFFICULTY_AI_ULTIMATE,
    NUMBER_OF_DIFFICULTY_AI,
};

// These should match the resource list in order
enum {
    HAR_NAME_JAGUAR = 0,
    HAR_NAME_SHADOW,
    HAR_NAME_THORN,
    HAR_NAME_PYROS,
    HAR_NAME_ELECTRA,
    HAR_NAME_KATANA,
    HAR_NAME_SHREDDER,
    HAR_NAME_FLAIL,
    HAR_NAME_GARGOYLE,
    HAR_NAME_CHRONOS,
    HAR_NAME_NOVA,
};

enum {
    PILOT_NAME_CRYSTAL = 0,
    PILOT_NAME_STEFFAN,
    PILOT_NAME_MILANO,
    PILOT_NAME_CHRISTIAN,
    PILOT_NAME_SHIRRO,
    PILOT_NAME_JEANPAUL,
    PILOT_NAME_IBRAHIM,
    PILOT_NAME_ANGEL,
    PILOT_NAME_COSSETTE,
    PILOT_NAME_RAVEN,
    PILOT_NAME_KREISSACK,
};

enum {
    ROUND_TYPE_ONE = 0,
    ROUND_TYPE_2_OF_3,
    ROUND_TYPE_3_OF_5,
    ROUND_TYPE_4_OF_7,
    NUMBER_OF_ROUND_TYPES
};

#endif // _COMMON_DEFINES_H