#include "formats/tag_list.h"
#include "formats/script_tag.h"

// This file is generated automatically

const tag_descriptor tag_descriptor_list[] = {
    [TAG_AA] = {"aa",  0, "Reset your air attack state if you have already performed one"                              },
    [TAG_AB] = {"ab",  0, "Allow passing through walls"                                                                },
    [TAG_AC] = {"ac",  0, "Turn the HAR to face the center of the arena"                                               },
    [TAG_AD] = {"ad",  0, " Allow the HAR to turn in the held direction. Used in Katana's wall spin and Heel Stomp"    },
    [TAG_AE] = {"ae",  0, NULL                                                                                         },
    [TAG_AF] = {"af",  0, "Freeze opponent HAR"                                                                        },
    [TAG_AG] = {"ag",  0, NULL                                                                                         },
    [TAG_AI] = {"ai",  0, "Hit will launch"                                                                            },
    [TAG_AM] = {"am",  0, "With the enemy modifier, 'ame' is related to the bm tag and tells OMF when to stop walking" },
    [TAG_AO] = {"ao",  0, "Nova death related, something to do with loose robot parts ?"                               },
    [TAG_AS] = {"as",  0, "Makes the fire orb 'wander' in the fire pit b"                                              },
    [TAG_AT] = {"at",  0, "Sets object position behind enemy har, used only by chronos' teleport"                      },
    [TAG_AW] = {"aw",  0, "Tells if the HAR can pass through walls"                                                    },
    [TAG_AX] = {"ax",  0, "Ignore the ground and fall through the floor"                                               },
    [TAG_AR] = {"ar",  0, "Reverse player direction"                                                                   },
    [TAG_AL] = {"al",  0, NULL                                                                                         },
    [TAG_B] = {"b",   0, NULL                                                                                         },
    [TAG_B1] = {"b1",  0, "Advances you to fight Fire, and on Fire's stage advances you to fight Ice"                  },
    [TAG_B2] = {"b2",  0, "Breaks the grate on the floor of the Fire Pit, if it is breakable"                          },
    [TAG_BB] = {"bb",  1, "Vertical screen shake"                                                                      },
    [TAG_BE] = {"be",  0, "Block the end of the round, used in scrap/destruct"                                         },
    [TAG_BF] = {"bf",  1, "Blend finish"                                                                               },
    [TAG_BH] = {"bh",  0, "Possibly used to ignore bounds checking"                                                    },
    [TAG_BL] = {"bl",  1, "Horizontal screen shake with magnitude n"                                                   },
    [TAG_BM] = {"bm",  1, "Animation to play while doing something"                                                    },
    [TAG_BJ] = {"bj",  1, "Jump to animation <n>"                                                                      },
    [TAG_BS] = {"bs",  1, "Blend start"                                                                                },
    [TAG_BU] = {"bu",  0, "Used by jaguar's destruct to move to center of arena"                                       },
    [TAG_BW] = {"bw",  0, NULL                                                                                         },
    [TAG_BX] = {"bx",  0, NULL                                                                                         },
    [TAG_BPD] = {"bpd", 1, "Reference palette index"                                                                    },
    [TAG_BPS] = {"bps", 1, "Start palette index"                                                                        },
    [TAG_BPN] = {"bpn", 1, "Palette entry count"                                                                        },
    [TAG_BPF] = {"bpf", 0, "Fighter palette selection"                                                                  },
    [TAG_BPP] = {"bpp", 1, "Initial and final color level"                                                              },
    [TAG_BPB] = {"bpb", 1, "Initial color level"                                                                        },
    [TAG_BPO] = {"bpo", 0, "Disable palette effects"                                                                    },
    [TAG_BZ] = {"bz",  0, "Color tint effect"                                                                          },
    [TAG_BA] = {"ba",  1, "Credits fade effect remapping (?)"                                                          },
    [TAG_BC] = {"bc",  1, "Credits fade effect color count"                                                            },
    [TAG_BD] = {"bd",  0, "Credits fade effect switch"                                                                 },
    [TAG_BG] = {"bg",  0, "Credits fade effect unknown"                                                                },
    [TAG_BI] = {"bi",  1, "Credits fade effect color start index"                                                      },
    [TAG_BK] = {"bk",  1, NULL                                                                                         },
    [TAG_BN] = {"bn",  0, "Unblockable move"                                                                           },
    [TAG_BO] = {"bo",  1, NULL                                                                                         },
    [TAG_BR] = {"br",  0, "Draw additively"                                                                            },
    [TAG_BT] = {"bt",  0, "Dark tint, used by shadow HAR"                                                              },
    [TAG_BY] = {"by",  0, NULL                                                                                         },
    [TAG_CF] = {"cf",  0, "Only used by shadow scrap, works with 'bm' tag to walk to far corner of arena"              },
    [TAG_CG] = {"cg",  0,
                "Triggers behaviors when touching the ground. Used by Katana Corkscrew Blade. (Enables the d<> tag)"   },
    [TAG_CL] = {"cl",  0, "Triggers the next animation when touching the ground. Used by Pyros to proceed with scrap." },
    [TAG_CP] = {"cp",  0, "If hit collision succeeds, perform hit pause"                                               },
    [TAG_CW] = {"cw",  0,
                "Enables a wall collision for the enemy and triggers a hit. Used in Flail's scrap to automatically "
                "trigger jn"                                                                                           },
    [TAG_CX] = {"cx",  1,
                "The player has horizontal control by holding left/right. Larger numbers mean faster movement"         },
    [TAG_CY] = {"cy",  1, "The player has vertical control by holding up/down. Larger numbers mean faster movement"    },
    [TAG_D] = {"d",   1, "Re-enter animation at N ticks.  If negative, enter animation this many ticks from the end"  },
    [TAG_E] = {"e",   0, "Set position to enemy position"                                                             },
    [TAG_F] = {"f",   0, "Flip sprite vertically"                                                                     },
    [TAG_G] = {"g",   0, "Set position to ground and zero velocity"                                                   },
    [TAG_H] = {"h",   0, "Set velocity to 0; applied every tick"                                                      },
    [TAG_I] = {"i",   0, "Move is interrupted on block"                                                               },
    [TAG_JF2] = {"jf2", 0, "Allow chaining to destruction"                                                              },
    [TAG_JF] = {"jf",  0, "Allow chaining to scrap"                                                                    },
    [TAG_JG] =
        {"jg",  0,
                "Every HAR uses this in the 'getup' animation, purpose unknown, might be 'grab' (like standing throw)?"},
    [TAG_JH] = {"jh",  0, "Allow chaining to 'high' moves"                                                             },
    [TAG_JJ] = {"jj",  0, "Allow chaining to airborne moves"                                                           },
    [TAG_JL] = {"jl",  0, "Allow chaining to 'low' moves"                                                              },
    [TAG_JM] = {"jm",  0, "Allow chaining to 'mid' moves"                                                              },
    [TAG_JP] = {"jp",  0, "Allow chaining to 'projectile' moves, not used"                                             },
    [TAG_JZ] = {"jz",  0, "Combination of all other j flags except jn"                                                 },
    [TAG_JN] = {"jn",  1, "Allow frame to chain to animation N"                                                        },
    [TAG_K] = {"k",   1, "Knockback on hit"                                                                           },
    [TAG_L] = {"l",   1, "Sound loudness"                                                                             },
    [TAG_MA] = {"ma",  1, "Sets angle of new object in degrees. Velocity is then x=cos(ma), y=sin(ma)."                },
    [TAG_MC] = {"mc",  0, NULL                                                                                         },
    [TAG_MD] = {"md",  1, "Destroy animation N"                                                                        },
    [TAG_MG] = {"mg",  1, "Gravity for spawned animation, default 0"                                                   },
    [TAG_MI] = {"mi",  1, "Instance count for spawned animation, default 1"                                            },
    [TAG_MM] = {"mm",  1, "Selects an animation ID for use with mo, mu tags."                                          },
    [TAG_MN] = {"mn",  1, NULL                                                                                         },
    [TAG_MO] = {"mo",  0, "Enables some flag on animation selected with MM. Possibly used on other HAR ?"              },
    [TAG_MP] = {"mp",  1, "Feature bitmask"                                                                            },
    [TAG_MRX] = {"mrx", 1, "Randomize new animation X"                                                                  },
    [TAG_MRY] = {"mry", 1, "Randomize new animation Y"                                                                  },
    [TAG_MS] = {"ms",  0, "Set special Y position for object; y = -4 * (y - 188)"                                      },
    [TAG_MU] = {"mu",  1, "Sets animation MM unavailable for use for the next <n> ticks"                               },
    [TAG_MX] = {"mx",  1, "X position of new animation"                                                                },
    [TAG_MY] = {"my",  1, "Y position of new animation"                                                                },
    [TAG_M] = {"m",   1, "Create instance of animation N"                                                             },
    [TAG_N] = {"n",   0, "Disable collision detection for the current frame"                                          },
    [TAG_OX] = {"ox",  1, "Set sprite X correction for this frame"                                                     },
    [TAG_OY] = {"oy",  1, "Set sprite Y correction for this frame"                                                     },
    [TAG_PA] = {"pa",  0, "Enable color effect for HAR palette effects"                                                },
    [TAG_PB] = {"pb",  1, "N < 512"                                                                                    },
    [TAG_PC] = {"pc",  1, "N < 512"                                                                                    },
    [TAG_PD] = {"pd",  1, "n < 256. Reference color index."                                                            },
    [TAG_PE] = {"pe",  0, "Switch HAR palette effect handling to the other HAR."                                       },
    [TAG_PH] = {"ph",  0, "Disable HAR palette effects if HAR is not in damage animation (9)"                          },
    [TAG_PP] = {"pp",  1, "Effect intensity"                                                                           },
    [TAG_PS] = {"ps",  0, "Update the color palette"                                                                   },
    [TAG_PTD] = {"ptd", 1, "Effect fade-in time in ticks (0-127)"                                                       },
    [TAG_PTP] = {"ptp", 1, "Effect constant max-value time in ticks (0-127)"                                            },
    [TAG_PTR] = {"ptr", 1, "Effect fade-out time in ticks (0-127)"                                                      },
    [TAG_Q] = {"q",   1, "Enable hit on current and next n-1 frames."                                                 },
    [TAG_R] = {"r",   0, "Flip sprite horizontally"                                                                   },
    [TAG_S] = {"s",   1, "Play sound N from sound table footer"                                                       },
    [TAG_SA] = {"sa",  0, NULL                                                                                         },
    [TAG_SB] = {"sb",  1, "Sound panning start"                                                                        },
    [TAG_SC] = {"sc",  1, NULL                                                                                         },
    [TAG_SD] = {"sd",  0, NULL                                                                                         },
    [TAG_SE] = {"se",  1, "Sound panning end 1"                                                                        },
    [TAG_SF] = {"sf",  1, "Sound frequency"                                                                            },
    [TAG_SL] = {"sl",  1, "Sound panning end 2"                                                                        },
    [TAG_SMF] = {"smf", 1, "Stop playing music track N"                                                                 },
    [TAG_SMO] = {"smo", 1, "Play music track N"                                                                         },
    [TAG_SP] = {"sp",  1, NULL                                                                                         },
    [TAG_SW] = {"sw",  1, NULL                                                                                         },
    [TAG_T] = {"t",   0, "Prevent sound from playing if other HAR is blocking"                                        },
    [TAG_U] = {"u",   0, "Bring sprite to the front"                                                                  },
    [TAG_UA] = {"ua",  0,
                "Sets enemy HAR to a damage animation and sets the enemy HAR's animation timing to match yours."       },
    [TAG_UB] = {"ub",  0, "Motion blur effect"                                                                         },
    [TAG_UC] = {"uc",  0, NULL                                                                                         },
    [TAG_UD] = {"ud",  0, NULL                                                                                         },
    [TAG_UE] = {"ue",  0, "Damage enemy if on the ground"                                                              },
    [TAG_UF] = {"uf",  0,
                "Only used by shadow grab (both forms) and shadow scrap. May have to do with opponent's ground state." },
    [TAG_UG] = {"ug",  0, NULL                                                                                         },
    [TAG_UH] = {"uh",  0, NULL                                                                                         },
    [TAG_UJ] = {"uj",  0, NULL                                                                                         },
    [TAG_UL] = {"ul",  0, NULL                                                                                         },
    [TAG_UN] = {"un",  0, "Disable cornerpush behavior"                                                                },
    [TAG_UR] = {"ur",  0, "If the opponent is blocking, force them to stay blocking."                                  },
    [TAG_US] = {"us",  0, NULL                                                                                         },
    [TAG_UZ] = {"uz",  0, "Used in shadow grab. Causes the shadow to disappear when the opponent takes damage"         },
    [TAG_V] = {"v",   0, "Velocity modifier for x/y"                                                                  },
    [TAG_VSX] = {"vsx", 0, NULL                                                                                         },
    [TAG_VSY] = {"vsy", 0, NULL                                                                                         },
    [TAG_W] = {"w",   0, "Push sprite to the back"                                                                    },
    [TAG_X_MINUS] = {"x-",  1, "Set X coordinate to -N"                                                                     },
    [TAG_X_PLUS] = {"x+",  1, "Set X coordinate to +N"                                                                     },
    [TAG_X_EQ] = {"x=",  1, "Interpolate X coordinate to N by next frame"                                                },
    [TAG_X] = {"x",   1, "Scale image as % of width (default 100)"                                                    },
    [TAG_Y_MINUS] = {"y-",  1, "Set Y coordinate to -N"                                                                     },
    [TAG_Y_PLUS] = {"y+",  1, "Set Y coordinate to +N"                                                                     },
    [TAG_Y_EQ] = {"y=",  1, "Interpolate Y coordinate to N by next frame"                                                },
    [TAG_Y] = {"y",   1, "Scale image as % of height (default 100)"                                                   },
    [TAG_ZG] = {"zg",  0, "Never used?"                                                                                },
    [TAG_ZH] = {"zh",  0, "Never used?"                                                                                },
    [TAG_ZJ] = {"zj",  0, "Invulnerable to jumping attacks"                                                            },
    [TAG_ZL] = {"zl",  0, "Never used?"                                                                                },
    [TAG_ZM] = {"zm",  0, "Never used?"                                                                                },
    [TAG_ZP] = {"zp",  0, "Invulnerable to projectiles"                                                                },
    [TAG_ZZ] = {"zz",  0, "Invulnerable to any attacks"                                                                },
};

const int tag_descriptor_count = 153;
