#include "formats/taglist.h"
#include <stddef.h>

// This file is generated automatically

const sd_tag sd_taglist[] = {
    {"aa",  0, "Reset your air attack state if you have already performed one"                                        },
    {"ab",  0, "Allow passing through walls"                                                                          },
    {"ac",  0, "Turn the HAR to face the center of the arena"                                                         },
    {"ad",  0, " Allow the HAR to turn in the held direction. Used in Katana's wall spin and Heel Stomp"              },
    {"ae",  0, NULL                                                                                                   },
    {"af",  0, "Freeze opponent HAR"                                                                                  },
    {"ag",  0, NULL                                                                                                   },
    {"ai",  0, "Hit will launch"                                                                                      },
    {"am",  0, "With the enemy modifier, 'ame' is related to the bm tag and tells OMF when to stop walking"           },
    {"ao",  0, "Nova death related, something to do with loose robot parts ?"                                         },
    {"as",  0, "Makes the fire orb 'wander' in the fire pit b"                                                        },
    {"at",  0, "Sets object position behind enemy har, used only by chronos' teleport"                                },
    {"aw",  0, "Tells if the HAR can pass through walls"                                                              },
    {"ax",  0, "Ignore the ground and fall through the floor"                                                         },
    {"ar",  0, "Reverse player direction"                                                                             },
    {"al",  0, NULL                                                                                                   },
    {"b",   0, NULL                                                                                                   },
    {"b1",  0, "Advances you to fight Fire, and on Fire's stage advances you to fight Ice"                            },
    {"b2",  0, "Breaks the grate on the floor of the Fire Pit, if it is breakable"                                    },
    {"bb",  1, "Vertical screen shake"                                                                                },
    {"be",  0, "Block the end of the round, used in scrap/destruct"                                                   },
    {"bf",  1, "Blend finish"                                                                                         },
    {"bh",  0, "Possibly used to ignore bounds checking"                                                              },
    {"bl",  1, "Horizontal screen shake with magnitude n"                                                             },
    {"bm",  1, "Animation to play while doing something"                                                              },
    {"bj",  1, "Jump to animation <n>"                                                                                },
    {"bs",  1, "Blend start"                                                                                          },
    {"bu",  0, "Used by jaguar's destruct to move to center of arena"                                                 },
    {"bw",  0, NULL                                                                                                   },
    {"bx",  0, NULL                                                                                                   },
    {"bpd", 1, "Reference palette index"                                                                              },
    {"bps", 1, "Start palette index"                                                                                  },
    {"bpn", 1, "Palette entry count"                                                                                  },
    {"bpf", 0, "Fighter palette selection"                                                                            },
    {"bpp", 1, "Initial and final color level"                                                                        },
    {"bpb", 1, "Initial color level"                                                                                  },
    {"bpo", 0, "Disable palette effects"                                                                              },
    {"bz",  0, "Color tint effect"                                                                                    },
    {"ba",  1, "Credits fade effect remapping (?)"                                                                    },
    {"bc",  1, "Credits fade effect color count"                                                                      },
    {"bd",  0, "Credits fade effect switch"                                                                           },
    {"bg",  0, "Credits fade effect unknown"                                                                          },
    {"bi",  1, "Credits fade effect color start index"                                                                },
    {"bk",  1, NULL                                                                                                   },
    {"bn",  0, "Unblockable move"                                                                                     },
    {"bo",  1, NULL                                                                                                   },
    {"br",  0, "Draw additively"                                                                                      },
    {"bt",  0, "Dark tint, used by shadow HAR"                                                                        },
    {"by",  0, NULL                                                                                                   },
    {"cf",  0, "Only used by shadow scrap, works with 'bm' tag to walk to far corner of arena"                        },
    {"cg",  0, NULL                                                                                                   },
    {"cl",  0, NULL                                                                                                   },
    {"cp",  0, "If hit collision succeeds, perform hit pause"                                                         },
    {"cw",  0, NULL                                                                                                   },
    {"cx",  1, "The player has horizontal control by holding left/right. Larger numbers mean faster movement"         },
    {"cy",  1, "The player has vertical control by holding up/down. Larger numbers mean faster movement"              },
    {"d",   1, "Re-enter animation at N ticks"                                                                        },
    {"e",   0, "Set position to enemy position"                                                                       },
    {"f",   0, "Flip sprite vertically"                                                                               },
    {"g",   0, "Set position to ground and zero velocity"                                                             },
    {"h",   0, "Set velocity to 0; applied every tick"                                                                },
    {"i",   0, "Move is interrupted on block"                                                                         },
    {"jf2", 0, "Allow chaining to destruction"                                                                        },
    {"jf",  0, "Allow chaining to scrap"                                                                              },
    {"jg",  0, "Every HAR uses this in the 'getup' animation, purpose unknown, might be 'grab' (like standing throw)?"},
    {"jh",  0, "Allow chaining to 'high' moves"                                                                       },
    {"jj",  0, "Allow chaining to airborne moves"                                                                     },
    {"jl",  0, "Allow chaining to 'low' moves"                                                                        },
    {"jm",  0, "Allow chaining to 'mid' moves"                                                                        },
    {"jp",  0, NULL                                                                                                   },
    {"jz",  0, "Combination of all other j flags except jn"                                                           },
    {"jn",  1, "Allow frame to chain to animation N"                                                                  },
    {"k",   1, "Knockback on hit"                                                                                     },
    {"l",   1, "Sound loudness"                                                                                       },
    {"ma",  1, "Sets angle of new object in degrees. Velocity is then x=cos(ma), y=sin(ma)."                          },
    {"mc",  0, NULL                                                                                                   },
    {"md",  1, "Destroy animation N"                                                                                  },
    {"mg",  1, "Gravity for spawned animation, default 0"                                                             },
    {"mi",  1, "Instance count for spawned animation, default 1"                                                      },
    {"mm",  1, "Selects an animation ID for use with mo, mu tags."                                                    },
    {"mn",  1, NULL                                                                                                   },
    {"mo",  0, "Enables some flag on animation selected with MM. Possibly used on other HAR ?"                        },
    {"mp",  1, "Feature bitmask"                                                                                      },
    {"mrx", 1, "Randomize new animation X"                                                                            },
    {"mry", 1, "Randomize new animation Y"                                                                            },
    {"ms",  0, "Set special Y position for object; y = -4 * (y - 188)"                                                },
    {"mu",  1, "Sets animation MM unavailable for use for the next <n> ticks"                                         },
    {"mx",  1, "X position of new animation"                                                                          },
    {"my",  1, "Y position of new animation"                                                                          },
    {"m",   1, "Create instance of animation N"                                                                       },
    {"n",   0, "Disable collision detection for the current frame"                                                    },
    {"ox",  1, "Set sprite X correction for this frame"                                                               },
    {"oy",  1, "Set sprite Y correction for this frame"                                                               },
    {"pa",  0, "Enable color effect for HAR palette effects"                                                          },
    {"pb",  1, "N < 512"                                                                                              },
    {"pc",  1, "N < 512"                                                                                              },
    {"pd",  1, "n < 256. Reference color index."                                                                      },
    {"pe",  0, "Switch HAR palette effect handling to the other HAR."                                                 },
    {"ph",  0, "Disable HAR palette effects if HAR is not in damage animation (9)"                                    },
    {"pp",  1, "Effect intensity"                                                                                     },
    {"ps",  0, "Update the color palette"                                                                             },
    {"ptd", 1, "Effect fade-in time in ticks (0-127)"                                                                 },
    {"ptp", 1, "Effect constant max-value time in ticks (0-127)"                                                      },
    {"ptr", 1, "Effect fade-out time in ticks (0-127)"                                                                },
    {"q",   1, "Enable hit on current and next n-1 frames."                                                           },
    {"r",   0, "Flip sprite horizontally"                                                                             },
    {"s",   1, "Play sound N from sound table footer"                                                                 },
    {"sa",  0, NULL                                                                                                   },
    {"sb",  1, "Sound panning start"                                                                                  },
    {"sc",  1, NULL                                                                                                   },
    {"sd",  0, NULL                                                                                                   },
    {"se",  1, "Sound panning end 1"                                                                                  },
    {"sf",  1, "Sound frequency"                                                                                      },
    {"sl",  1, "Sound panning end 2"                                                                                  },
    {"smf", 1, "Stop playing music track N"                                                                           },
    {"smo", 1, "Play music track N"                                                                                   },
    {"sp",  1, NULL                                                                                                   },
    {"sw",  1, NULL                                                                                                   },
    {"t",   0, "Prevent sound from playing if other HAR is blocking"                                                  },
    {"u",   0, "Bring sprite to the front"                                                                            },
    {"ua",  0, "Sets enemy HAR to damage animation, if not already set."                                              },
    {"ub",  0, "Motion blur effect"                                                                                   },
    {"uc",  0, NULL                                                                                                   },
    {"ud",  0, NULL                                                                                                   },
    {"ue",  0, "Damage enemy if on the ground"                                                                        },
    {"uf",  0, NULL                                                                                                   },
    {"ug",  0, NULL                                                                                                   },
    {"uh",  0, NULL                                                                                                   },
    {"uj",  0, NULL                                                                                                   },
    {"ul",  0, NULL                                                                                                   },
    {"un",  0, NULL                                                                                                   },
    {"ur",  0, NULL                                                                                                   },
    {"us",  0, NULL                                                                                                   },
    {"uz",  0, "Used in shadow grab. Causes the shadow to disappear when the opponent takes damage"                   },
    {"v",   0, "Velocity modifier for x/y"                                                                            },
    {"vsx", 0, NULL                                                                                                   },
    {"vsy", 0, NULL                                                                                                   },
    {"w",   0, "Push sprite to the back"                                                                              },
    {"x-",  1, "Set X coordinate to -N"                                                                               },
    {"x+",  1, "Set X coordinate to +N"                                                                               },
    {"x=",  1, "Interpolate X coordinate to N by next frame"                                                          },
    {"x",   1, "Scale image as % of width (default 100)"                                                              },
    {"y-",  1, "Set Y coordinate to -N"                                                                               },
    {"y+",  1, "Set Y coordinate to +N"                                                                               },
    {"y=",  1, "Interpolate Y coordinate to N by next frame"                                                          },
    {"y",   1, "Scale image as % of height (default 100)"                                                             },
    {"zg",  0, "Never used?"                                                                                          },
    {"zh",  0, "Never used?"                                                                                          },
    {"zj",  0, "Invulnerable to jumping attacks"                                                                      },
    {"zl",  0, "Never used?"                                                                                          },
    {"zm",  0, "Never used?"                                                                                          },
    {"zp",  0, "Invulnerable to projectiles"                                                                          },
    {"zz",  0, "Invulnerable to any attacks"                                                                          },
};

const int sd_taglist_size = 153;
