#include <stdlib.h>
#include "shadowdive/taglist.h"

// This file is generated automatically

static const sd_tag sd_tags[] = {
    {"aa", 0, NULL},
    {"ab", 0, NULL},
    {"ac", 0, NULL},
    {"ad", 0, NULL},
    {"ae", 0, NULL},
    {"af", 0, NULL},
    {"ag", 0, NULL},
    {"ai", 0, NULL},
    {"am", 0, NULL},
    {"ao", 0, NULL},
    {"as", 0, NULL},
    {"at", 0, NULL},
    {"aw", 0, NULL},
    {"ax", 0, NULL},
    {"ar", 0, NULL},
    {"al", 0, NULL},
    {"b", 0, NULL},
    {"b1", 0, NULL},
    {"b2", 0, NULL},
    {"bb", 1, "Vertical screen shake"},
    {"be", 0, NULL},
    {"bf", 1, "Blend finish"},
    {"bh", 0, NULL},
    {"bl", 1, NULL},
    {"bm", 1, NULL},
    {"bj", 1, NULL},
    {"bs", 1, "Blend start"},
    {"bu", 0, NULL},
    {"bw", 0, NULL},
    {"bx", 0, NULL},
    {"bpd", 1, "Reference palette index"},
    {"bps", 1, "Start palette index"},
    {"bpn", 1, "Palette entry count"},
    {"bpf", 0, "Fighter palette selection"},
    {"bpp", 1, "Initial and final color level"},
    {"bpb", 1, "Initial color level"},
    {"bpo", 0, "Disable palette effects"},
    {"bz", 0, "Color tint effect"},
    {"ba", 1, NULL},
    {"bc", 1, NULL},
    {"bd", 0, NULL},
    {"bg", 0, NULL},
    {"bi", 1, NULL},
    {"bk", 1, NULL},
    {"bn", 0, NULL},
    {"bo", 1, NULL},
    {"br", 0, "Draw additively?"},
    {"bt", 0, NULL},
    {"by", 0, NULL},
    {"cf", 0, NULL},
    {"cg", 0, NULL},
    {"cl", 0, NULL},
    {"cp", 0, "Apply damage?"},
    {"cw", 0, NULL},
    {"cx", 1, NULL},
    {"cy", 1, NULL},
    {"d", 1, "Re-enter animation at N ticks"},
    {"e", 0, "Relative enemy position modifier"},
    {"f", 0, "Flip sprite vertically?"},
    {"g", 0, NULL},
    {"h", 0, "Hover"},
    {"i", 0, NULL},
    {"jf2", 0, "Allow chaining to destruction"},
    {"jf", 0, "Allow chaining to scrap"},
    {"jg", 0, NULL},
    {"jh", 0, "Allow chaining to 'high' moves"},
    {"jj", 0, "Allow chaining to airborne moves"},
    {"jl", 0, "Allow chaining to 'low' moves"},
    {"jm", 0, "Allow chaining to 'mid' moves"},
    {"jp", 0, NULL},
    {"jz", 0, "Allow chaining to anything? (Katana head stomp)"},
    {"jn", 1, "Allow frame to chain to animation N"},
    {"k", 1, "Knockback on hit"},
    {"l", 1, "Sound loudness"},
    {"ma", 1, NULL},
    {"mc", 0, NULL},
    {"md", 1, "Destroy animation N?"},
    {"mg", 1, "Gravity for spawned animation"},
    {"mi", 1, NULL},
    {"mm", 1, NULL},
    {"mn", 1, NULL},
    {"mo", 0, NULL},
    {"mp", 1, NULL},
    {"mrx", 1, NULL},
    {"mry", 1, NULL},
    {"ms", 0, NULL},
    {"mu", 1, NULL},
    {"mx", 1, "X position of new animation"},
    {"my", 1, "Y position of new animation"},
    {"m", 1, "Create instance of animation N"},
    {"n", 0, NULL},
    {"ox", 1, NULL},
    {"oy", 1, NULL},
    {"pa", 0, "Enable color effect for HAR palette effects"},
    {"pb", 1, "N < 512"},
    {"pc", 1, "N < 512"},
    {"pd", 1, "n < 256. Reference color index."},
    {"pe", 0, "Switch HAR palette effect handling to the other HAR."},
    {"ph", 0, "Disable HAR palette effects if HAR is not in damage animation (9)"},
    {"pp", 1, "Duration of HAR palette effect in ticks."},
    {"ps", 0, "Update the color palette"},
    {"ptd", 1, "n < 128 Effect intensity."},
    {"ptp", 1, "N < 128"},
    {"ptr", 1, "N < 128"},
    {"q", 1, "Enable hit on current and next n-1 frames."},
    {"r", 0, "Flip sprite horizontally?"},
    {"s", 1, "Play sound N from sound table footer"},
    {"sa", 0, NULL},
    {"sb", 1, "Sound panning start"},
    {"sc", 1, NULL},
    {"sd", 0, NULL},
    {"se", 1, "Sound panning end 1"},
    {"sf", 1, "Sound frequency"},
    {"sl", 1, "Sound panning end 2"},
    {"smf", 1, "Stop playing music track N"},
    {"smo", 1, "Play music track N"},
    {"sp", 1, NULL},
    {"sw", 1, NULL},
    {"t", 0, NULL},
    {"ua", 0, "Disable gravity for opponent"},
    {"ub", 0, "Motion blur effect?"},
    {"uc", 0, NULL},
    {"ud", 0, NULL},
    {"ue", 0, "Damage enemy if on the ground"},
    {"uf", 0, NULL},
    {"ug", 0, NULL},
    {"uh", 0, NULL},
    {"uj", 0, NULL},
    {"ul", 0, NULL},
    {"un", 0, NULL},
    {"ur", 0, NULL},
    {"us", 0, NULL},
    {"uz", 0, NULL},
    {"v", 0, "Velocity modifier for x/y"},
    {"vsx", 0, NULL},
    {"vsy", 0, NULL},
    {"w", 0, NULL},
    {"x-", 1, "Decrement X coordinate by N"},
    {"x+", 1, "Increment X coordinate by N"},
    {"x=", 1, "Interpolate X coordinate to N by next frame"},
    {"x", 1, "Set X to N (N defaults to 100)?"},
    {"y-", 1, "Decrement Y coordinate by N"},
    {"y+", 1, "Increment Y coordinate by N"},
    {"y=", 1, "Interpolate Y coordinate to N by next frame"},
    {"y", 1, "Set Y to N (N defaults to 100)?"},
    {"zg", 0, "Never used?"},
    {"zh", 0, "Never used?"},
    {"zj", 0, "Invulnerable to jumping attacks?"},
    {"zl", 0, "Never used?"},
    {"zm", 0, "Never used?"},
    {"zp", 0, "Invulnerable to projectiles?"},
    {"zz", 0, "Invulnerable to any attacks?"},
};
