name: Functional CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:

  # Run rec tests and menu tests
  # -----------------------------------------------------------------------------------------------
  rec_and_menu_tests:
    name: Run rec tests and menu tests
    runs-on: ubuntu-24.04
    env:
      clang-version: '18'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install dependencies
      uses: Eeems-Org/apt-cache-action@v1.3
      with:
        packages: cmake cmake-data ninja-build libcunit1-dev
          libsdl2-mixer-dev libconfuse-dev libenet-dev libsdl2-dev libxmp-dev
          libpng-dev libopusfile-dev libepoxy-dev
          clang-${{ env.clang-version }}

    - name: Build tests
      run: |
        cmake -DCMAKE_C_COMPILER=clang-${{ env.clang-version }} \
              -DUSE_SANITIZERS=On \
              -DUSE_FATAL_SANITIZERS=On \
              -DUSE_MINIUPNPC=Off \
              -DUSE_NATPMP=Off \
              -G "Ninja Multi-Config" \
              -S . -B build-test
        cmake --build build-test -j $(getconf _NPROCESSORS_ONLN)

    - name: Get OMF2097 assets
      uses: ./.github/actions/assets

    - name: Extract omf 2097 assets
      run: unzip -j omf2097-assets.zip -d build-test/resources

    - name: Run rec tests
      run: ./run_rectests.sh build-test

    - name: Install pytest requirements
      run: |
        pipx install poetry
        poetry install

    - name: Run menu tests
      run: ./run_pytest.sh build-test
